name: Build and deploy ASP.Net Core app to Azure Web App - claro-auth-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: 🔧 Build with dotnet
        run: dotnet build Claro.AuthService.Api/Claro.AuthService.Api.csproj --configuration Release

      - name: 🚀 dotnet publish
        run: dotnet publish Claro.AuthService.Api/Claro.AuthService.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --runtime linux-x64 --self-contained false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_355BE53EFBE04C2FB836C718E66C76ED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CFAD6452F8A7461F82033BE9B73E2D83 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8C99C7EE0CB44D009B58E6B266F73FCB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'claro-auth-app'
          slot-name: 'Production'
          package: .
